blank_issues_enabled: false
contact_links:
  - name: Umbraco Community forum
    url: https://our.umbraco.com/
    about: "For community (free) support questions, please use the Umbraco Community forum."
  - name: "Commericial support"
    url: https://umbrellainc.co.uk/
    about: "For commerical (paid) support questions, please contact me via my company, Umbrella."
